name: Auto Publish

on:
  push:
    paths: index.html
    branches:
      - main
  pull_request: {}

jobs:
  validate-and-publish:
    name: Validate and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: w3c/spec-prod@v2 # use the action
        with:
          W3C_ECHIDNA_TOKEN: ${{ secrets.ECHIDNA_TOKEN }}
          # Please use the URL that's appropriate for your working group!
          W3C_WG_DECISION_URL: "https://lists.w3.org/Archives/Public/public-webrtc/2016Mar/0031.html"
          W3C_NOTIFICATIONS_CC: "dom@w3.org"
          VALIDATE_LINKS: false
          W3C_BUILD_OVERRIDE: |
            shortName: audio-output
            specStatus: CRD
